retry:
  max-retry: 3

server:
  port: 8080
  servlet:
    context-path: /argusweb

services:
  rest:
    auth-api: http://localhost:8081/authapi
  grpc:
    auth-api: localhost:8090

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  mongodb:
    embedded:
      version: 4.0.2