grpc:
  server:
    port: 8090

security:
  jwt:
    refresh_expiration: 600000
    expiration: 300000
    secret: secret
  secret-key: SQ56EgzwqTOddVKy3c3bfqugDkUxRxqy546Dc7eeLhAz3bARXHNc
  secret-size: 20

server:
  port: 8080
  servlet:
    context-path: /authapi

service-urls:
  customer-service: http://localhost:8080/argusweb/customers

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  mongodb:
    embedded:
      version: 4.0.2