grpc:
  server:
    port: ${APP_GRPC_PORT}

security:
  jwt:
    refresh_expiration: ${REFRESH_JWT_EXPIRATION}
    expiration: ${JWT_EXPIRATION}
    secret: ${JWT_SECRET}
  secret-key: ${SECRET_KEY}
  secret-size: ${SECRET_SIZE}

server:
  port: ${APP_PORT}
  servlet:
    context-path: /authapi

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}